name: taufiqsejati_travel
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  connectivity_plus: ^6.1.2
  d_method: null
  dartz: ^0.10.1
  equatable: ^2.0.7
  extended_image: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_rating_bar: ^4.0.1
  get_it: ^8.0.3
  google_fonts: null
  http: ^1.3.0
  intl: ^0.20.2
  photo_view: ^0.15.0
  shared_preferences: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
